# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  # 🌏 No need to update stats too frequently
  schedule: [{ cron: "0 0 * * *" }]
  # 💡 Allow running workflow manually from action tab
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_visibility: all
          plugin_activity_filter: push, issue, pr, release, fork, review, ref/create, public
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: assets/base.svg
          output_action: pull-request
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Langs
        uses: lowlighter/metrics@latest
        with:
          filename: assets/langs-all.svg
          output_action: pull-request
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          plugin_languages_aliases: RenderScript:Rust
          plugin_languages_ignored: Nix
          plugin_languages_recent_days: 14
      - name: Langs Indepth Programming
        uses: lowlighter/metrics@latest
        with:
          filename: assets/langs-indepth-programming.svg
          output_action: pull-request
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          plugin_languages_aliases: RenderScript:Rust
          plugin_languages_ignored: Nix
      - name: Langs Recent
        uses: lowlighter/metrics@latest
        with:
          filename: assets/langs-recent.svg
          output_action: pull-request-squash
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_indepth: yes
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          plugin_languages_aliases: RenderScript:Rust
          plugin_languages_ignored: Nix
          plugin_languages_recent_days: 365